### ISSUE TITLE
External cohort Pipeline Problem.

### ISSUE THREAD

**Issue by wuyu-z** [AdalbertoCq/Histomorphological-Phenotype-Learning#2]
Hello,@AdalbertoCq
I am trying run through the pipeline of Mapping an external cohort to existing clusters. For simplicity I am using just one WSI image as the external cohort.
On [**Step 4 including metadata in h5**](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/master/README_additional_cohort.md), I notice a csv file contains "luad", "os_event_ind", "os_event_data" column. I cannot create my own csv file, Where are these data come from? I secrch around and find nothing.

Might a silly question :)

Thank you

**Comment by AdalbertoCq** [comment]
Hey @wuyu-z , 
Those are the field related to each WSI or patient:

1. luad: Binary variable, one for lung adenocarcinoma and zero for lung squamous cell carcinoma. 
2. os_event_ind: Binary variable, one if the patient died and zero if it was censored.
3. os_event_data: Continuous variable in months. This is the time of the event, either time of death or censored time.

The values in the TCGA file come from the [GDC website](https://gdc.cancer.gov/). This [notebook](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/master/utilities/fold_creation/survival_folds.ipynb) shows how the survival data was processed from the raw TCGA values.

Hope this helps,
Adal

**Comment by wuyu-z** [comment]
Thank for your help and question solved, and apologize for bothering again. I do have another question. 
On step 5 Background and artifact removal of external cohort, you mentioned a file **hdf5_TCGAFFPE_LUADLUSC_5x_60pc_he_complete_lungsubtype_survival.h5**.
I understand this file is the output of normal HPL step 5 include metadata, but on the link you give it only has a post-filtered version. The link in [Step 5](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/master/README_HPL.md#5-include-metadata-in-h5-file) of [TCGA tile vector representations](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/master/README_HPL.md#TCGA-tile-vector-representations) is directing to nowhere. 
Can you upload a pre-filtered version?

Thank you
Wuyu

**Comment by AdalbertoCq** [comment]
No problem @wuyu-z , the link should be fixed now referencing the TCGA tile vector representations in the Readme.md. 

With respect to the unfiltered version, it will take a couple of days to upload that file but you should have it by Friday end of the day.

Thanks,
Adal

**Comment by AdalbertoCq** [comment]
Hey @wuyu-z , 

You should be able to find the file hdf5_TCGAFFPE_LUADLUSC_5x_60pc_he_complete_lungsubtype_survival.h5 with the unfiltered background and artifact on the [Reame.md](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/master/README.md#TCGA-HPL-files).

Thanks,
Adal

**Comment by wuyu-z** [comment]
Hi @AdalbertoCq,
Now my purpose is try to create a single given WSI image with HPC cluster overlay, like what you showed in the paper.
<img width="478" alt="capture" src="https://user-images.githubusercontent.com/98522338/187172478-92839ef2-35ca-47ab-b5ae-7099433cc45c.png">

Now I have done up to step 7 in the external cohort, and I now obtain csv files that a number assigned for each tile. I am assuming that is cluster id of that tile.
<img width="659" alt="1661766191586" src="https://user-images.githubusercontent.com/98522338/187173299-318a91e0-41e1-4c99-b45f-4363cce4f671.png">
 
Now I am losing track of what to produce the HPC cluster overlay image. What are the following procedure to produce the images?

Thank you very much
Wuyu

**Comment by AdalbertoCq** [comment]
Hey @wuyu-z ,

I have included `Get tiles and WSI samples for HPCs` in the [README_additional_cohort.md](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/master/README_additional_cohort.md). 

Right now, this step returns WSIs based on cluster contribution % or random selection from the total. If you want to create overlays for a specific slide, you will have to tinker with the code a bit. In [line 391 of clusters.py](https://github.com/AdalbertoCq/Histomorphological-Phenotype-Learning/blob/00125b98b884264990168cc3b7f747d726bf0758/models/visualization/clusters.py#L391), you should be able to modify the _slide_ variable to be the specific name of your slide. 

Thanks,
Adal
