### ISSUE TITLE
Magnification pre-trained models

### ISSUE THREAD

**Issue by marcovarrone** [AdalbertoCq/Histomorphological-Phenotype-Learning#5]
Hi, very nice work!

I want to extract the feature vectors for some of my H&E data, on tiles directly at 20x magnification.
However, I have seen that the pre-trained models have been trained on a 5x downscaled version of the images.

Have you ever tested the feature encoding for images with no downscaling?
Is it going to cause problems?

Thank you very much in advance

**Comment by AdalbertoCq** [comment]
Hi Marco, 

We did some work at 20x too and we have the pre-trained model, give me a couple of days and they should be available. The performance was similar in the LUAD tasks, it should show up in newer versions of the manuscript. 

I'll give an update in a couple of days.

Thanks,
Adal

**Comment by AdalbertoCq** [comment]
Hi @marcovarrone, 

You can find the LUAD 20x pre-trained model here: https://figshare.com/articles/dataset/HPL_LUAD_20x/25295638

Thanks,
Adal
